version: '3.7'
services:
  server:
    build: ./server
    expose:
      - 8080
    command: gunicorn server:server_web --bind localhost:8080 --worker-class aiohttp.GunicornWebWorker
    volumes:
    - static:/app

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
    - static:/app
    depends_on:
      - server

volumes:
  static:
