version: "3"
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web/app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env
  db:
    image: library/postgres:10-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
